export { default as AboutPage } from './about/AboutPage.tsx'
export { default as CartPage } from './cart'
export { default as ComboPage } from './combo'
export { default as ConstuctorPage } from './constructor'
export { default as HomePage } from './home'
export { default as LoginPage } from './login'
export { default as NotFoundPage } from './not-found'
